### ISSUE TITLE
I need to edit the Workshop page.

### ISSUE THREAD

**Issue by francopestilli** [IUNetSci/acnn-website#2]
Can one of you help me get started with editing the workshop page, please?

- Dates September 8-9 2017 (arrival September 7, evening)
- Keynote Speakers:
  - Randy Buckner (https://cnl.rc.fas.harvard.edu/)
  - Terry Jernigan (http://www.cogsci.ucsd.edu/~jernigan/)
  - Vince Calhoun (http://www.mrn.org/people/http-www.mrn.org-people-vince-calhoun-principal-investigators/principal-investigators)
  - Brian Wandell (https://web.stanford.edu/group/vista/cgi-bin/wandell/) 

- Invited speakers:
  - Olaf Sporns, Indiana University
  - Ivo Dinov, University of Michigan
  - DK Panda, Ohio State University
  - Satya Sahoo, Case Western University
  - Lei Wang, Northwestern University
  - Richard Gonzalez, University of Michigan
  - Franco Pestilli, Indiana University
 
- Lightning talks:

- Scholarships available.

- Abstract submission deadline.

**Comment by benserrette** [comment]
made changes here: ce49f50e2af31eb38679997e288e139de114a211

**Comment by christianbriggs** [comment]
Hello @francopestilli, 
@benabus has made the changes above, which can be viewed at https://iunetsci.github.io/acnn-website/ACNN_Workshop_2017.html before we push them live. Can you verify that these are correct, and we will update the live site? 

Thanks!

**Comment by francopestilli** [comment]
Thanks!

See details changes below:
- Dates September, 2017 ==> Dates September 8-9 2017
- Accommodation	Biddle Hotel Indiana Memorial Union (URL: https://imu.indiana.edu/hotel/)
- Travel Scholarships	50+ scholarships for trainees will be offered on a competitive base.
- URL https://iunetsci.github.io/acnn-website/ACNN_Workshop_2017.html
- Administrative: Alison Martin (aalison@med.umich.edu) or Programmatic: Ivo Dinov TO BE CHANGED TO Administrative: Mary Morgan (mcmorgan@indiana.edu) or Programmatic: Franco Pestilli franpest@indiana.edu

**Comment by christianbriggs** [comment]
I have made the changes, which can be viewed at https://iunetsci.github.io/acnn-website/ACNN_Workshop_2017.html 

@francopestilli, if everything looks good, please close this issue with a comment and @benabus  will push the changes to the live server.

**Comment by francopestilli** [comment]
A couple of comments:

(1) Can we make the names links instead of adding the link on the side?
[Randy Buckner](https://cnl.rc.fas.harvard.edu/)
[Terry Jernigan](http://www.cogsci.ucsd.edu/~jernigan/)
[Vince Calhoun](http://www.mrn.org/people/http-www.mrn.org-people-vince-calhoun-principal-investigators/principal-investigators)
[Brian Wandell](https://web.stanford.edu/group/vista/cgi-bin/wandell/)

(2) Add invited speaker:
Andrew Saykin, Indiana University School of Medicine

Thanks!

**Comment by christianbriggs** [comment]
Good suggestions. The changes are made. @benabus would you push them to the live site?

**Comment by christianbriggs** [comment]
The changes are now live on http://www.neurosciencenetwork.org/ACNN_Workshop_2017.html. Let us know if there is anything amiss.
